version: "3.7"

services:
  backend:
    image: alexisbellido/python:3.7.6
    command: development
    ports:
      - "8000:8000"
    environment:
      - FLASK_APP=emailer
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=8000
      - REDIS_HOST=0.0.0.0
      - REDIS_PORT=6379
    volumes:
      # bind mount for development
      - type: bind
        source: ./flask/project
        target: /root/project
  frontend:
    image: node:14.4.0-stretch
    command: npm start
    ports:
      - "3000:3000"
    stdin_open: true
    working_dir: /root/simon-templar
    volumes:
      # bind mount for development
      - type: bind
        source: ./react/simon-templar
        target: /root/simon-templar
      - type: bind
        source: ./react/simon-templar/node_modules
        target: /root/simon-templar/node_modules
        consistency: cached
